[package]
name = "tidas-validation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
jsonschema.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tidas-assets = { path = "../tidas-assets" }
tidas-runtime = { path = "../tidas-runtime" }

[lints]
workspace = true
